FORMAT: 1A
HOST: /api

# Todo Mock API

Todo アプリのモック API のドキュメントです。
かなり変更される可能性があるため、バージョンを確認してください。

# Group ユーザー認証

## 登録 [/users]

### 登録 [POST]
+ Request (application/json)
    + Body

            {
                "user": "admin",
                "password": "SuperSecretPassword"
            }

+ Response 200 (application/json)
    + Body

            {
                "message": "User registration completed"
            }

## ログイン [/users/login]

### ログイン [POST]
認証用のトークンを発行する

+ Request (application/json)
    + Body

            {
                "email": "admin",
                "password": "SuperSecretPassword"
            }

+ Response 200 (application/json)
    + Body 

            {
                "token": "{token}"
            }

# Group タスク

## 一覧 [/tasks]

### 一覧取得 [GET]
+ Request
    + Headers

            Authorization: Bearer {token}

+ Response 200 (application/json)

        [
            {
                "id": "asgsngasasdfkjasdfas",
                "title": "SampleTask",
                "detail": "SampleDetail",
                "is_complete": false,
                "created_at": "2022-06-26T07:55:21.109Z"
            },
            {
                "id": "ASdfjasdfasdflkAsdfj",
                "title": "SampleTask2",
                "is_complete": false,
                "created_at": "2022-06-27T08:20:11.109Z"
            }
        ]

+ Response 401 (application/json)

            { "error": "Unauthorized" }

### 登録 [POST]
+ Request (application/json)
    + Headers

            Authorization: Bearer {token}
    + Body

            {
                "title": "SampleTask",
                "detail": "SampleDetail",
            }

+ Response 200 (application/json)

        {
            "id": "asgsngasasdfkjasdfas",
            "title": "SampleTask",
            "detail": "SampleDetail",
            "is_complete": false,
            "created_at": "2022-06-26T07:55:21.109Z"
        },

+ Response 401 (application/json)

            { "error": "Unauthorized" }

## 個別 [/tasks/{id}]

### 取得 [GET]
+ Parameters
    + id: asgsngasasdfkjasdfas (string) - タスク ID
+ Request
    + Headers

            Authorization: Bearer {token}

+ Response 200 (application/json)

        {
            "id": "asgsngasasdfkjasdfas",
            "title": "SampleTask",
            "detail": "SampleDetail",
            "is_complete": false,
            "created_at": "2022-06-26T07:55:21.109Z"
        },

+ Response 401 (application/json)

            { "error": "Unauthorized" }

+ Response 404 (application/json)

            { "error": "Not Found" }

### 更新 [PATCH]
+ Parameters
    + id: asgsngasasdfkjasdfas (string) - タスク ID
+ Request (application/json)
    + Headers

            Authorization: Bearer {token}
    + Body

            {
                "title": "SampleHogeTask",
                "detail": "SampleDetail",
            }

+ Response 200 (application/json)

        {
            "id": "asgsngasasdfkjasdfas",
            "title": "SampleHogeTask",
            "detail": "SampleDetail",
            "is_complete": false,
            "created_at": "2022-06-26T07:55:21.109Z"
        },

+ Response 401 (application/json)

            { "error": "Unauthorized" }

+ Response 404 (application/json)

            { "error": "Not Found" }

### 削除 [DELETE]
+ Parameters
    + id: asgsngasasdfkjasdfas (string) - タスク ID
+ Request
    + Headers

            Authorization: Bearer {token}

+ Response 200 (application/json)

        {
            "message": "Successfully deleted"
        }
+ Response 401 (application/json)

        { "error": "Unauthorized" }

+ Response 404 (application/json)

            { "error": "Not Found" }

## タスク完了 [/tasks/{id}/completion]

### 完了 [PUT]
+ Parameters
    + id: asgsngasasdfkjasdfas (string) - タスク ID
+ Request
    + Headers

            Authorization: Bearer {token}

+ Response 200 (application/json)

        {
            "id": "asgsngasasdfkjasdfas",
            "title": "SampleHogeTask",
            "detail": "SampleDetail",
            "is_complete": true,
            "created_at": "2022-06-26T07:55:21.109Z"
        },

+ Response 401 (application/json)

            { "error": "Unauthorized" }

+ Response 404 (application/json)

            { "error": "Not Found" }

### 完了取り消し [DELETE]
+ Parameters
    + id: asgsngasasdfkjasdfas (string) - タスク ID
+ Request
    + Headers

            Authorization: Bearer {token}

+ Response 200 (application/json)

        {
            "id": "asgsngasasdfkjasdfas",
            "title": "SampleHogeTask",
            "detail": "SampleDetail",
            "is_complete": false,
            "created_at": "2022-06-26T07:55:21.109Z"
        },

+ Response 401 (application/json)

            { "error": "Unauthorized" }

+ Response 404 (application/json)

            { "error": "Not Found" }